// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNodZpglKBA34YwSLaLHl4DkSVartZn8',
    appId: '1:1027926499273:web:a91882abf19e5261575218',
    messagingSenderId: '1027926499273',
    projectId: 'skillworker-20386',
    authDomain: 'skillworker-20386.firebaseapp.com',
    storageBucket: 'skillworker-20386.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1CUCzbAGIH0imyZKOvxJce9vPY73K6k',
    appId: '1:1027926499273:android:51cf87b21abfbc19575218',
    messagingSenderId: '1027926499273',
    projectId: 'skillworker-20386',
    storageBucket: 'skillworker-20386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSJ1NsMdLDCH49HoF_VIrUBr9et5zbwM',
    appId: '1:1027926499273:ios:237c460ca1ced524575218',
    messagingSenderId: '1027926499273',
    projectId: 'skillworker-20386',
    storageBucket: 'skillworker-20386.appspot.com',
    iosBundleId: 'com.example.skillworker',
  );
}
